model_name_or_path: /mnt/gemininjceph2/geminicephfs/wx-mm-spr-xxxx/zhanghanlei/llm_checkpoints/Qwen2-VL-7B-Instruct
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

dataset: AnnoMi-therapist_train_communication_behavior_llamafactory
dataset_dir: /mnt/gemininjceph2/geminicephfs/wx-mm-spr-xxxx/zhanghanlei/MMLA/src/Finetune/Frameworks/LLaMA-Factory-main/data
eval_dataset: AnnoMi-therapist_dev_communication_behavior_llamafactory
template: qwen2_vl
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 1

output_dir: /mnt/gemininjceph2/geminicephfs/wx-mm-spr-xxxx/zhanghanlei/models_sft/AnnoMi-therapist/communication_behavior/Qwen2-VL-7B-Instruct_SFT
logging_steps: 10
save_steps: 5
plot_loss: true
overwrite_output_dir: true
compute_accuracy: true

per_device_train_batch_size: 8
gradient_accumulation_steps: 4
learning_rate: 1.0e-3
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.2
bf16: true
ddp_timeout: 180000000

per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 5
